[package]
name = "todo"
version = "0.1.0"
authors = ["Fergus Molloy <fergus@molloy.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
dirs = "3.0.1"
rusqlite = "0.24.2"
structopt = "0.3.21"
